source "https://rubygems.org"

- # use local theme gem for testing
- gem "minimal-mistakes-jekyll", path: "../"
+ gem "minimal-mistakes-jekyll", "~> 4.24.0"

group :jekyll_plugins do
  gem 'jekyll-algolia', '~> 1.0'
end

gem "wdm", "~> 0.1.0" if Gem.win_platform?
gem "jekyll", "~> 4.2"
gem "webrick"      # Jekyll 실행 시 필요
gem "bigdecimal"   # Jekyll(Liquid 필터)이 필요로 함
gem "csv"          # Jekyll에서 필요
gem "base64"       # 일부 라이브러리에서 필요
